// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | media
//    input  | Controller_Buttons_Left_Trigger_LT.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_Controller_Buttons_Left_Trigger_LT_length;
extern const uint8_t  gfx_Controller_Buttons_Left_Trigger_LT[75];
