// Copyright 2025 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `painter_convert_graphics` with arguments:
//    format | mono2
//    output | media
//    input  | Software_Image_File_Picture_Framed_Painting_Landscape_Photo_Decoration.png

#pragma once

#include <qp.h>

extern const uint32_t gfx_Software_Image_File_Picture_Framed_Painting_Landscape_Photo_Decoration_length;
extern const uint8_t  gfx_Software_Image_File_Picture_Framed_Painting_Landscape_Photo_Decoration[73];
